### ISSUE TITLE
✔ Feat: 어드민 페이지 배너 관리 기능 추가

### ISSUE THREAD

**Issue by lgkrwnsdll** [jigumulmi/backend#144]
## Description
배너: 서비스 메인 페이지에 장소 큐레이션을 주로 담당

어드민 페이지를 위한 관리 기능 우선 개발

## Todo
- [x] Banner 엔티티 생성 및 장소와 다대다 관계로 연결
    - 컬럼: 외부 이미지, 내부 이미지, 이름, 활성화 여부, Timestamp
- [x] Banner 생성
- [x] Banner 리스트 조회
- [x] Banner 연관된 장소 추가
- [x] Banner 연관된 장소 제거
- [x] Banner 상세 조회
- [x] Banner에 연관된 장소 목록 조회 -> 쿼리 효율을 위해 배너 상세 조회와 분리 (UI 상 탭으로 나눠도 좋을듯)
- [x] Banner 정보 수정 (연관 장소 제외)
- [x] Banner 이미지 수정
- [x] Banner 삭제
- [x] 할당 후보 장소 목록 조회
- [x] 배너 클릭수 저장 및 조회 설계
---
- 장소
- [x] Place 테이블에 시군구 컬럼 추가 -> 자바 ENUM으로 관리
- [x] 장소 리스트 API에 업체명 검색 시 contains 사용

## Etc
- [x] 연관 장소 대표 장소 및 순서 존재 여부 확인
- [x] 장소 시군구 필터링의 경우 1차로 서울/경기/인천 선택 후 인풋창 자동완성
- [x] 배너 생성 및 수정 시 이미지 처리 방법 결정
> [!IMPORTANT]
> 백엔드 입장에서 생성 API는 파일로 받든 presigned URL 방식으로 하든 상관 없고, 수정 API가 문제 
> PUT으로 할 경우 클라이언트에서 수정하지 않은 이미지도 다시 보내야하며 PATCH는 원래 까다로움
1. PATCH
2. 생성, 수정 둘다 presigned URL 방식
3. 생성은 파일로 받고, 수정만 presigned URL 방식
4. 수정 API에서 이미지 관련 API 분리 -> 이미지 덮어쓸때만 요청
    - HTTP PUT: 외부 이미지 수정 API. 내부 이미지 수정 API
    - HTTP PATCH: 이미지 수정 단일 API

**Comment by lgkrwnsdll** [comment]
연관 장소 대표 장소 및 순서 존재 여부 확인
- 대표 장소 현재는 없고 순서는 좋아요, 이름 순

**Comment by lgkrwnsdll** [comment]
presigned URL API는 상황에 맞게 별도 생성

**Comment by lgkrwnsdll** [comment]
배너 생성 API -> 모든 요소
배너 수정 API -> 1. 이름, 활성화여부 2. 외부 이미지 3. 내부 이미지
