### ISSUE TITLE
✔ Feat: ELK 도입

### ISSUE THREAD

**Issue by lgkrwnsdll** [jigumulmi/backend#148]
## Description
사용자 활동 로그 분석을 위한 파이프라인 구축

## Todo
- [x] EC2에 filebeat 설치
- [x] filebeat에서 OpenSearch로 바로 로그 전송
- [x] filebeat exclude_lines,[ decode_json_fields, drop_fields, add_fields](https://betterstack.com/community/guides/logging/filebeat-explained/) 설정
- [x] OpenSearch Visualization으로 간단한 통계 확인

## Etc
- LogStash와 Kibana는 서버 자원과 복잡성 이슈로 우선 보류

**Comment by lgkrwnsdll** [comment]
systemd에 등록하여 백그라운드로 구동

filebeat input type을 filestream -> log로 수정하여 exclude_lines 활성화
