### ISSUE TITLE
✔ Feat: 실서버 배포 시 작업 사항

### ISSUE THREAD

**Issue by lgkrwnsdll** [jigumulmi/backend#159]
## Description
spring boot actuator 및 로그 저장 파이프라인 도입으로 처리해야할 작업
신규 기능 도입에 따른 작업

## Todo
- [x] 배포 워크플로우 수정 (개발 서버와 동일하게)
- [x] 모니터링 시스템 워크플로우 추가

### 새로운 AWS 계정에 기존 계정 AWS 자원 이전
- [x] VPC Peering
- [x] ALB, 대상그룹
- [x] EC2
- EC2 내부 디렉토리 구조 고려 (/tmp, ~~/filebeat~~, deploy.sh, jar), [swap 메모리 설정](https://repost.aws/knowledge-center/ec2-memory-swap-file)
- ec2 ~~git pull permission 에러 해결~~, docker 설치
- [x] Route53, ACM
- [x] ~~기존 개발 서버 계정 EC2 private 서브넷으로 이전~~
- swap 메모리, 개발 서버 배포 워크플로우 수정
- [x] RDS
- github actions 러너에서 테스트 코드 수행 가능한지 확인
- [ ] S3, CloudFront, IAM(s3 사용자)

### 로그 파이프라인
- [x] application.properties
- actuator 설정, multipart tmp 디렉토리 (jigumulmi/tmp/multipart)
- [x] deploy.sh 수정

### 데이터 세팅
- [ ] 실디비 Place 테이블에 행정구역 관련 데이터 추가 스크립트 실행
- [ ] 실디비 영업시간 관련 테이블에 기존 데이터 마이그레이션 스크립트 제작 및 실행

## Etc
- [x] RDS, ALB, EC2 프라이빗하게 할 수 있는 지 확인
- 개발서버 AWS 계정은 내년 3월까지 유지
- #150 은 신규 AWS 계정에서 처리

**Comment by lgkrwnsdll** [comment]
#148
