### ISSUE TITLE
✔ Feat: Fluentbit, Loki, Prometheus, Grafana

### ISSUE THREAD

**Issue by lgkrwnsdll** [jigumulmi/backend#161]
## Description
시스템 메트릭 및 애플리케이션 로그 모니터링 시스템 구축
- 주요 목적: 사용자 활동 추적 및 애플리케이션 에러 로그 확인
- 추후 성능 테스트 시 K6 활용해 grafana와 연동 #145 

## Todo
- [x] fluentbit으로 로컬 로그 loki에 전송
- [x] loki로 로그 수집 및 s3 전송
- [x] prometheus로 메트릭 데이터 수집
- [x] grafana로 데이터 확인
- [x] loki, prometheus compactor
- [ ] prometheus에서 RDS 시스템 메트릭 수집
- [x] 관리자 인원 IP 수집 -> FluentBit에서 제외 #186 

## Etc
- 기존 filebeat, OpenSearch 파이프라인 제거 #148 
- 추후 alert 정책 추가
- rds slow query 혹은 error log 수집 방식

**Comment by lgkrwnsdll** [comment]
password.txt와 .env는 수동으로 처리
